site_name: Bodega Esports Platform
theme:
  name: material

plugins:
  - search
  - monorepo

nav:
  - Backend:
      - Overview: backend/docs/README.md
      - Summary: backend/docs/SUMMARY.md
      - Changelog: backend/docs/CHANGELOG.md
  - Frontend:
      - Overview: frontend/docs/README.md
      - Summary: frontend/docs/SUMMARY.md
      - Changelog: frontend/docs/CHANGELOG.md
  - Auth Service:
      - Overview: auth-service/docs/README.md
      - Summary: auth-service/docs/SUMMARY.md
      - Changelog: auth-service/docs/CHANGELOG.md
  - Discord Bot:
      - Overview: discord-bot/docs/README.md
      - Summary: discord-bot/docs/SUMMARY.md
      - Changelog: discord-bot/docs/CHANGELOG.md
