services:
  - type: web
    name: bodega-esports-backend
    env: python
    plan: free
    region: oregon
    rootDir: .                     # <- use repo root now
    buildCommand: |
      pip install -r requirements.txt
      npm install
      npm run build
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:7Rkv9NHoMcgqfx7@db.kvkmepmsloyekfqwdcgq.supabase.co:5432/postgres
      - key: PORT
        value: 10000
