services:
  - type: web
    name: bodega-esports-backend
    env: python
    plan: free
    region: virginia
    rootDir: .  # deploying from repo root
    buildCommand: |
      pip install -r requirements.txt
      npm install
      npm run build
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:7Rkv9NHoMcgqfx7@db.kvkmepmsloyekfqwdcgq.supabase.co:5432/postgres
      - key: PORT
        value: 10000
  - type: web
    name: bodega-esports-frontend
    runtime: node
    plan: free
    region: virginia
    rootDir: frontend
    buildCommand: npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: VITE_API_URL
        value: https://bodega-esports-backend.onrender.com
