services:
  - type: web
    name: bodega-esports-backend
    env: python
    plan: starter
    region: virginia
    rootDir: backend  # Backend service is rooted at the backend folder
    buildCommand: |
      # Install Python dependencies and cache them
      if [ ! -d ".venv" ]; then python -m venv .venv; fi
      . .venv/bin/activate
      pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: PORT
        value: ${PORT:-10000}
  - type: web
    name: bodega-esports-frontend
    runtime: node
    plan: starter
    region: virginia
    rootDir: frontend  # Frontend service is rooted at the frontend folder
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://bodega-esports-backend.onrender.com
        # Each service is run out of its respective folder to ensure dependencies, environment, and build artifacts are isolated.
