site_name: Backend Docs (internal)
docs_dir: docs        # if you’ve put your markdown in backend/docs/
# └─ OR, if your files are directly under backend/app/api/, use:
# docs_dir: app/api

nav:
  - Read Me: Backend-README.md
  - Changelog: Backend-CHANGELOG.md