name: Deploy Frontend to Cloudways

on:
  push:
    branches:
      - mono

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Upload frontend using RSYNC over SSH
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avz --delete
          path: frontend/dist/
          remote_path: /home/master/applications/5455430/public_html/
          remote_host: ${{ secrets.CLOUDWAYS_SSH_HOST }}
          remote_user: ${{ secrets.CLOUDWAYS_SSH_USER }}
          remote_key: ${{ secrets.CLOUDWAYS_SSH_KEY }}
