name: Deploy Frontend to Cloudways

on:
  push:
    branches:
      - mono

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Upload frontend using SSH and rsync
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLOUDWAYS_SSH_HOST }}
          username: ${{ secrets.CLOUDWAYS_SSH_USER }}
          port: ${{ secrets.CLOUDWAYS_SSH_PORT }}
          key: ${{ secrets.CLOUDWAYS_SSH_KEY }}
          script: |
            echo "Cleaning public_html first..."
            rm -rf /home/master/applications/5455430/public_html/*
            echo "Uploading new frontend build..."
            rsync -avz frontend/dist/ /home/master/applications/5455430/public_html/
