name: Deploy Frontend to Cloudways

on:
  push:
    branches:
      - mono

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build
      
      - name: Deploy to Cloudways
        uses: appleboy/scp-action@mono
        with:
          host: ${{ secrets.CLOUDWAYS_SSH_HOST }}
          username: ${{ secrets.CLOUDWAYS_SSH_USERNAME }}
          port: ${{ secrets.CLOUDWAYS_SSH_PORT }}
          key: ${{ secrets.CLOUDWAYS_SSH_KEY }}
          source: "frontend/dist/*"
          target: ${{ secrets.CLOUDWAYS_DEPLOY_PATH }}
          overwrite: true
          rm: false
          debug: true
