name: Use Org Version + Changelog

on:
  push:
    branches:
      - react
  workflow_dispatch:

jobs:
  run-org-action:
    uses: BodegaCatsGC/github-actions/.github/workflows/version-and-changelog.yml@master
