name: version-and-changelog

on:
  push:

jobs:
  version-and-changelog:
    runs-on: [self-hosted, linux, arm64, docker]  # Or ubuntu-latest if not using the Pi

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: -1
      - name: Update CHANGELOG.md
        uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: ${{ github.repository }}
          Branch: React
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATH: 'CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update for v${{ steps.version.outputs.version }}'
          TYPE: 'feat:Features,fix:Bug Fixes,docs:Documentation,refactor:Refactors,perf:Performance Improvements, chore: chores'
          REGENERATE_COUNT: -1
          DEFAULT_SCOPE: 'general'

      - name: Calculate next semantic version
        id: version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          major_regexp_flags: ""
          minor_pattern: "(MINOR)"
          minor_regexp_flags: ""
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          bump_each_commit: true
          bump_each_commit_patch_pattern: ""
          search_commit_body: true
          enable_prerelease_mode: true
      
      - name: Git tag and push
        run: |
          git config --global user.email "bot@bodegacatsgc.gg"
          git config --global user.name "wersplat"
          git add CHANGELOG.md
          git commit -m "docs(CHANGELOG): update for v${{ steps.version.outputs.version }}"
          git tag v${{ steps.version.outputs.version }}
          git push origin react --tags
