# GitBook configuration for Bodega Esports Platform Discord Bot
root: ./README.md
summary: ./SUMMARY.md

# Optional: Add metadata, plugins, or customizations below as needed
# For example:
# title: Bodega Esports Platform Discord Bot Documentation
# plugins:
#   - search
#   - highlight
